#!/bin/bash

# Trim trailing slashes from input (necessary for grep)
DIRECTORY=$(echo $1 | sed 's:/*$::')

if [ -d "$DIRECTORY" ]; then
  cp -vR `ls -A | grep -v "^$DIRECTORY\$"` $DIRECTORY | cat -n
  echo "Files copied succesfully"
elif [[ -f $DIRECTORY ]]; then
  echo "$DIRECTORY is a file"
  exit 1
else
  echo "$DIRECTORY is not valid"
  exit 1
fi
